# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-31 10:03
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entity', '0001_initial'),
        ('osm', '0002_osm_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='OriginDestinationCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_inc', models.DateTimeField(db_index=True, null=True)),
                ('measures', django.contrib.postgres.fields.jsonb.JSONField()),
                ('osm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.PlanetOsmLine')),
            ],
        ),
        migrations.CreateModel(
            name='StreetTaxiCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_inc', models.DateTimeField(db_index=True, null=True)),
                ('measures', django.contrib.postgres.fields.jsonb.JSONField()),
                ('entity', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='entity.Entity')),
                ('osm', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='osm.PlanetOsmLine')),
            ],
        ),
        migrations.CreateModel(
            name='TimeIncrement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_time', models.DateTimeField(unique=True)),
                ('year', models.SmallIntegerField()),
                ('day_of_year', models.SmallIntegerField()),
                ('month', models.SmallIntegerField()),
                ('day_of_month', models.SmallIntegerField()),
                ('week', models.SmallIntegerField()),
                ('day_of_week', models.SmallIntegerField()),
                ('hour', models.SmallIntegerField()),
                ('workday', models.BooleanField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='streettaxicell',
            unique_together=set([('osm', 'entity', 'time_inc')]),
        ),
        migrations.AlterUniqueTogether(
            name='origindestinationcell',
            unique_together=set([('time_inc', 'osm')]),
        ),
    ]
