# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-18 20:48
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streetcube', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegionPartition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('geometry', django.contrib.gis.db.models.fields.PolygonField(null=True, srid=3857)),
                ('name', models.CharField(max_length=64, null=True)),
                ('items', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
            ],
        ),
    ]
