# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-09-07 00:55
from __future__ import unicode_literals

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pgrouting', '0004_osmnodes_osmrelations_osmwayclasses_osmwaytypes_relationsways_ways_waysverticespgr'),
        ('streetcube', '0003_auto_20170221_0108'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreetCell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_inc', models.DateTimeField(db_index=True, null=True)),
                ('measures', django.contrib.postgres.fields.jsonb.JSONField()),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pgrouting.Ways')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='origindestinationcell',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='origindestinationcell',
            name='osm',
        ),
        migrations.AlterUniqueTogether(
            name='streettaxicell',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='streettaxicell',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='streettaxicell',
            name='osm',
        ),
        migrations.AlterField(
            model_name='regionpartition',
            name='items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.BigIntegerField(), size=None),
        ),
        migrations.DeleteModel(
            name='OriginDestinationCell',
        ),
        migrations.DeleteModel(
            name='StreetTaxiCell',
        ),
        migrations.AlterUniqueTogether(
            name='streetcell',
            unique_together=set([('street', 'time_inc')]),
        ),
    ]
