# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 15:14
from __future__ import unicode_literals

from django.db import migrations

from osm import osm_loader


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('osm', '0001_initial')
    ]

    operations = [
        migrations.RunPython(osm_loader.forwards_func, osm_loader.reverse_func),
        migrations.RunSQL("""
            CREATE OR REPLACE FUNCTION osm_roadmatch_point(
                point geometry,
                initial_results integer DEFAULT 10)
            RETURNS bigint AS $BODY$
            DECLARE
                the_match bigint;
            BEGIN
                point := ST_Transform(point, 3857);
                SELECT l.gid, ST_Distance(l.way, point) as dist
                INTO the_match
                FROM planet_osm_line as l
                WHERE
                    ST_DWithin(point, l.way, 20)
                    AND
                    l.highway IN (
                        'motorway',
                        'trunk',
                        'primary',
                        'secondary',
                        'tertiary',
                        'unclassified',
                        'residential',
                        'service',
                        'motorway_link',
                        'trunk_link',
                        'primary_link',
                        'secondary_link',
                        'tertiary_link',
                        'living_street',
                        'road',
                        'turning_circle'
                    )
                ORDER BY dist
                LIMIT initial_results
                ;
                RETURN the_match;
            END $BODY$
            LANGUAGE plpgsql VOLATILE;""",
            "DROP FUNCTION osm_roadmatch_point(geometry, integer);"
        ),
        migrations.RunSQL("""
            CREATE FUNCTION osm_roadmatch_line(
                IN geometry,
                initial_results int DEFAULT 10)
            RETURNS bigint[] AS $BODY$
            DECLARE
                roadmatch bigint[];
            BEGIN
                SELECT array_agg(osm_roadmatch_point((dp).geom, initial_results)) INTO roadmatch
                FROM (SELECT ST_DumpPoints($1) AS dp) As foo;
                RETURN roadmatch;
            END $BODY$
            LANGUAGE plpgsql VOLATILE;""",
            "DROP FUNCTION osm_roadmatch_line(geometry, int)"
        ),
        migrations.RunSQL(
            "ALTER TABLE planet_osm_line ADD gid serial PRIMARY KEY;",
            "ALTER TABLE planet_osm_line DROP COLUMN gid"
        ),
        migrations.RunSQL(
            "ALTER TABLE planet_osm_roads ADD gid serial PRIMARY KEY;",
            "ALTER TABLE planet_osm_roads DROP COLUMN gid"
        ),
        migrations.RunSQL(
            "ALTER TABLE planet_osm_point ADD gid serial PRIMARY KEY;",
            "ALTER TABLE planet_osm_point DROP COLUMN gid"
        ),
        migrations.RunSQL(
            "ALTER TABLE planet_osm_polygon ADD gid serial PRIMARY KEY;",
            "ALTER TABLE planet_osm_polygon DROP COLUMN gid"
        ),
    ]
