# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-28 09:11
from __future__ import unicode_literals

from django.db import migrations

from pgrouting import loader


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunSQL(
            sql="""CREATE EXTENSION IF NOT EXISTS postgis;""",
            reverse_sql=''  # """DROP EXTENSION postgis;"""
        ),
        migrations.RunSQL(
            # pgrouting is easier to use if applied to the default 'public' schema
            sql="""CREATE EXTENSION IF NOT EXISTS pgrouting;""",
            reverse_sql=''  # """DROP EXTENSION pgrouting;"""
        ),
    ]
